import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import api, { messageFromError } from '../services/api'

export default function CreatePoll() {
  const navigate = useNavigate(); const [question, setQuestion] = useState(''); const [options, setOptions] = useState(['', '']); const [duration, setDuration] = useState('0'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const response = await api.post('/polls', { question, options, durationSeconds: Number(duration) }); navigate(`/polls/${response.data.poll.id}`) } catch (err) { setError(messageFromError(err, 'Unable to create poll')) } finally { setLoading(false) } }
  return <main className="content narrow"><Link className="back-link" to="/dashboard">← Dashboard</Link><p className="eyebrow">NEW POLL</p><h1>Put a question to the room.</h1><form className="poll-form" onSubmit={submit}><label>Question<textarea required minLength="5" maxLength="500" rows="3" placeholder="What do you want to know?" value={question} onChange={(e) => setQuestion(e.target.value)} /></label><div className="section-label"><span>Answer options</span><span>{options.length}/10</span></div>{options.map((option, index) => <div className="option-row" key={index}><span>{String(index + 1).padStart(2, '0')}</span><input required maxLength="200" placeholder={`Option ${index + 1}`} value={option} onChange={(e) => setOptions((items) => items.map((item, itemIndex) => itemIndex === index ? e.target.value : item))} />{options.length > 2 && <button type="button" className="icon-button" onClick={() => setOptions((items) => items.filter((_, itemIndex) => itemIndex !== index))}>×</button>}</div>)}{options.length < 10 && <button type="button" className="text-button" onClick={() => setOptions((items) => [...items, ''])}>＋ Add option</button>}<label>Poll timer<select value={duration} onChange={(e) => setDuration(e.target.value)}><option value="0">No timer</option><option value="60">1 minute</option><option value="300">5 minutes</option><option value="600">10 minutes</option><option value="1800">30 minutes</option><option value="3600">Custom: 60 minutes</option></select></label>{error && <p className="form-error">{error}</p>}<button className="button button-primary" disabled={loading}>{loading ? 'Creating...' : 'Create poll'}</button></form></main>
}
